### ISSUE TITLE
старайся придти к restful 

### ISSUE THREAD

**Issue by SixteenMissedCalls** [Aqualized/StalKompParser#1]
https://github.com/Aqualized/StalKompParser/blob/42f3a18eb0f5171782377a3fc21c3123f29dfd2d/StalKompParser/Controllers/StalController.cs#L7 тут url api не соответствует  ресту, надо что то типа `api/ресурс`

**Comment by Aqualized** [comment]
поменял на api/product с ендпоинтами:
-Post
/search
/details
