### ISSUE TITLE
поменять название 

### ISSUE THREAD

**Issue by SixteenMissedCalls** [Aqualized/StalKompParser#10]
https://github.com/Aqualized/StalKompParser/blob/42f3a18eb0f5171782377a3fc21c3123f29dfd2d/StalKompParser/StalKompParser/ProductParser.cs#L31

**Comment by SixteenMissedCalls** [comment]
например ParseInternal

**Comment by Aqualized** [comment]
Поменял название, но еще доработку веду парсера
