### ISSUE TITLE
лучше делай products.Any плюс почему product если множественное число и зачем добавляешь что то если там пустой лист

### ISSUE THREAD

**Issue by SixteenMissedCalls** [Aqualized/StalKompParser#13]
https://github.com/Aqualized/StalKompParser/blob/42f3a18eb0f5171782377a3fc21c3123f29dfd2d/StalKompParser/StalKompParser/ProductParser.cs#L62

**Comment by SixteenMissedCalls** [comment]
почитай как работает Any  тут тебе надо проверить просто на пустоту и нам нет смысла считать все объекты листа (а именно так работает count)

**Comment by Aqualized** [comment]
больше не issue, в коде больше такого нет
