### ISSUE TITLE
дубляж кода 

### ISSUE THREAD

**Issue by SixteenMissedCalls** [Aqualized/StalKompParser#15]
https://github.com/Aqualized/StalKompParser/blob/42f3a18eb0f5171782377a3fc21c3123f29dfd2d/StalKompParser/StalKompParser/StalKompItem.cs#L1-L76 зачем тебе два класса (два файла) один для загрузки станицы каталога, другой для товара. Сделай один класс, а page возращай черезщ фабрику, а этот базовый класс, как абстракцию, от которой наследуй уже классы для конкретной страницы

**Comment by Aqualized** [comment]
В процессе вместе с парсером красевеньким
