### ISSUE TITLE
хм я бы фабрику внедрял не через di

### ISSUE THREAD

**Issue by SixteenMissedCalls** [Aqualized/StalKompParser#17]
https://github.com/Aqualized/StalKompParser/blob/7ae16ecc82093515ce421e165d1283beb9b658a9/StalKompParser/Program.cs#L33

**Comment by Aqualized** [comment]
А что предлагаешь? я до этого в ногу себе стрельнул пытаясь создать крутую расширяемую фабрику для парсеров но обосрався и запутався

**Comment by Aqualized** [comment]
исправил, как и фул систему фабрик
