### ISSUE TITLE
такие модели приянто в конце помечать как response или Dto

### ISSUE THREAD

**Issue by SixteenMissedCalls** [Aqualized/StalKompParser#3]
https://github.com/Aqualized/StalKompParser/blob/42f3a18eb0f5171782377a3fc21c3123f29dfd2d/StalKompParser/Models/StalKompProduct.cs#L3

**Comment by Aqualized** [comment]
Поменял структуру моделей в последнем коммите, но не поменял парсер так что нихера не работает, зато модельки мне нравятся

**Comment by Aqualized** [comment]
Поменял модельки по документации
