### ISSUE TITLE
атрибуты валидации 

### ISSUE THREAD

**Issue by SixteenMissedCalls** [Aqualized/StalKompParser#4]
https://github.com/Aqualized/StalKompParser/blob/42f3a18eb0f5171782377a3fc21c3123f29dfd2d/StalKompParser/PageLoader/PageLoader.cs#L26 такие вещи модно вынести в [атрибуты валидации](https://metanit.com/sharp/aspnet5/19.2.php)

**Comment by Aqualized** [comment]
Отвалидачил
